listen_address: "127.0.0.1:1080"
server_address: "ghostproxy.duckdns.org:443"
server_name: "ghostproxy.duckdns.org"
ca_file: ""
log_level: "info"
fallback_address: ""
padding_enabled: true
jitter_ms: 0
